# Generated by Django 5.1.1 on 2024-10-01 22:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(related_name='projects', to='main.tag')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
