# Generated by Django 5.1.1 on 2024-10-02 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_featured',
            new_name='is_active',
        ),
    ]
