# Generated by Django 5.1.1 on 2025-03-18 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_blog_content_alter_project_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_count', models.IntegerField(default=0)),
                ('unique_visit_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36, unique=True)),
                ('visit_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_visitors', to='main.visittracker')),
            ],
        ),
    ]
