# Generated by Django 5.1.1 on 2025-05-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_userprofile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
