"""
Django settings for PersonalWebsite project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: never set DJANGO_DEBUG in production. Local: DJANGO_DEBUG=1 in .env.
DEBUG = os.getenv("DJANGO_DEBUG", "").strip().lower() in ("1", "true", "yes")
# With DEBUG off, static files only come from STATIC_ROOT after collectstatic.
WHITENOISE_USE_FINDERS = DEBUG

ALLOWED_HOSTS = ['*']
# Include apex and www so POSTs (e.g. contact/admin) pass CSRF checks from either host.
CSRF_TRUSTED_ORIGINS = [
    "https://haokai-xuan.com",
    "https://www.haokai-xuan.com",
]

SECURE_REFERRER_POLICY = "no-referrer-when-downgrade"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
    'ckeditor',
]

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 600,
        'width': '100%',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline', 'Link', 'Unlink'],
            ['Image', 'Embed', 'Iframe'],  # Allow Embed and Iframe
            ['NumberedList', 'BulletedList'],
            ['Cut', 'Copy', 'Paste', 'Undo', 'Redo'],
            ['Source'],
        ],
        'extraAllowedContent': 'iframe[*]',  # Allow iframes
        'extraPlugins': 'codesnippet,embed,autoembed,iframe,image2',  # Enable embed, iframe plugins, codesnippet
    }
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PersonalWebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PersonalWebsite.wsgi.application'


# Database & uploaded media on persistent disk (e.g. Railway volume).
# Local: leave DJANGO_DATA_DIR unset → project-root db.sqlite3 and ./media (unchanged).
# Production: mount a volume and set DJANGO_DATA_DIR to that path (e.g. /data).
_persist_dir = os.getenv("DJANGO_DATA_DIR", "").strip()
if _persist_dir:
    _persist_path = Path(_persist_dir)
    _persist_path.mkdir(parents=True, exist_ok=True)
    _sqlite_path = _persist_path / "db.sqlite3"
    _media_path = _persist_path / "media"
    _media_path.mkdir(parents=True, exist_ok=True)
else:
    _sqlite_path = BASE_DIR / "db.sqlite3"
    _media_path = BASE_DIR / "media"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _sqlite_path,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Where collectstatic will copy all static files
STATIC_ROOT = os.path.join(BASE_DIR, 'static_collected')
# Leading slash: URLs must be root-relative so nested pages (e.g. /blog/slug/) load assets correctly.
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'),  # Static files location in the root directory
]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.fspath(_media_path)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
